# Generated by Django 5.0.2 on 2024-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_orderproduct_quantity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='products'),
        ),
    ]
