# Generated by Django 5.0.2 on 2024-04-18 12:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='passport',
        ),
        migrations.AddField(
            model_name='product',
            name='press_release',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='press_releases'),
        ),
    ]
