# Generated by Django 5.0.2 on 2024-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_passport_product_press_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='press_release',
            field=models.FileField(upload_to='products'),
        ),
    ]
