# Generated by Django 5.0.2 on 2024-04-18 12:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_press_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='press_release',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='products'),
        ),
    ]
