# Generated by Django 5.0.2 on 2024-04-18 12:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='press_release',
        ),
        migrations.AddField(
            model_name='product',
            name='pasport',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='products', verbose_name='Паспорт'),
        ),
    ]
