# Generated by Django 5.0.2 on 2024-04-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_press_release_product_pasport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pasport',
            new_name='passport_pdf',
        ),
        migrations.AddField(
            model_name='product',
            name='passport_img',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Паспорт картинка'),
        ),
    ]
